login:
  homeserver_url: "https://matrix.example.com"
  username: "@wipbot:example.com"
  password: "REDACTED"
  device_name: "wip-bot"
users:
  # Much spam allowed
  vip:
    - "@admin:example.com"
  # A bit of spam allowed, invites allowed
  trusted:
    - "example.com"
    - "@trusted:sth.example.com"
bot:
  # If you want the bot to respond when mentioned at the message beginning, set this to the bot's display name
  plaintext_ping: "My-Bot-Name"
  text_spam:
    vip_limit: 500
    trusted_limit: 100
  sticker_spam:
    vip_limit: 500
    trusted_limit: 100
  typing:
    max_duration: 20
