login:
  homeserver_url: "https://matrix.example.com"
  username: "@wipbot:example.com"
  password: "REDACTED"
  device_name: "wip-bot"
  # Optional recovery key to verify the bot
  #recover_key: "E..."
users:
  # Much spam allowed
  vip:
    - "@admin:example.com"
  # A bit of spam allowed, invites allowed
  trusted:
    - "example.com"
    - "@trusted:sth.example.com"

# Optional: adjust where to persist data (mainly decryption keys)
#data_path: /opt/matrix-wip-bot

bot:
  # If you want the bot to respond when mentioned at the message beginning, set this to the bot's display name
  plaintext_ping: "My-Bot-Name"
  text_spam:
    vip_limit: 500
    trusted_limit: 100
  sticker_spam:
    vip_limit: 500
    trusted_limit: 100
  image_spam:
    vip_limit: 50
    trusted_limit: 20
    max_size: 2000
  delay_spam:
    # Seconds how long we're allowed to sum up spam delays for a single command
    limit: 30
  typing:
    max_duration: 20
tts:
  config_path: "/path/to/en_US-libritts_r-medium.onnx.json"
